version: "3.1"

services:
  mongo:
    container_name: mongo
    image: mongo:4.0
    restart: always
    ports:
      - 27345:27017
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - ./mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: cnmongoproductionuser
      MONGO_INITDB_ROOT_PASSWORD: GocCt7YNR8GTj2Xh
    networks:
      - default

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8055:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: cnmongoproductionuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: GocCt7YNR8GTj2Xh
      ME_CONFIG_BASICAUTH_USERNAME: cnmongodbclient
      ME_CONFIG_BASICAUTH_PASSWORD: p8EmxvbJFtRd7Ws2
    networks:
      - default
